//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTradingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuthenticate
    {
        public int id { get; set; }
        public Nullable<int> uid { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
