//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTradingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMarketdata
    {
        public int id { get; set; }
        public string stockName { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> currentPrice { get; set; }
        public string status { get; set; }
    }
}
