//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTradingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSessionsData
    {
        public int sessionId { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<System.DateTime> loginTime { get; set; }
        public Nullable<System.DateTime> logoutTime { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
