//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTradingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStocksHistory
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> stockId { get; set; }
        public Nullable<decimal> openingPrice { get; set; }
        public Nullable<decimal> closingPrice { get; set; }
        public Nullable<decimal> lowPrice { get; set; }
        public Nullable<decimal> highPrice { get; set; }
    
        public virtual tblStock tblStock { get; set; }
    }
}
