//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTradingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransact
    {
        public int transactionId { get; set; }
        public Nullable<int> buyerReqId { get; set; }
        public string buyerName { get; set; }
        public Nullable<int> sellerReqId { get; set; }
        public string sellerName { get; set; }
        public string stock { get; set; }
        public Nullable<decimal> buyPrice { get; set; }
        public Nullable<decimal> sellPrice { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    
        public virtual tblTradeRequest tblTradeRequest { get; set; }
        public virtual tblTradeRequest tblTradeRequest1 { get; set; }
    }
}
